# Licensed Materials - Property of IBM
# Text Toolkit for IBM Streams
# (c) Copyright IBM Corp. 2017
# All rights reserved.                               


.PHONY: all clean 

all:
	cd es_test; make all; cd -;

clean:
	cd es_test; make clean; cd -;

tkidx:
	cd es_test; make tkidx; cd -;
